"""Changes in Education Class

Revision ID: 39e44daa1c92
Revises: 917f7e8a27b8
Create Date: 2026-01-09 17:23:52.157192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e44daa1c92'
down_revision = '917f7e8a27b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degree_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('institute_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_column('institute_url')
        batch_op.drop_column('degree_type')

    # ### end Alembic commands ###
