"""Add education table

Revision ID: 917f7e8a27b8
Revises: 
Create Date: 2026-01-04 04:59:58.936662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917f7e8a27b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=False),
    sa.Column('institute', sa.String(length=200), nullable=False),
    sa.Column('start_year', sa.String(length=20), nullable=True),
    sa.Column('end_year', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    # ### end Alembic commands ###
